version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: zombie_apocalypse
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: zaq1@WSX
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/myapp
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: zombie_apocalypse
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: zaq1@WSX
